### ISSUE TITLE
Issues with API

### ISSUE THREAD

**Issue by systats** [stillmatic/leagueR#2]
Hi Chris, 

wonderful package. Exactly whatwe need right now ;) Unforntunatly I cant get it working. Im always getting the same error with each function:

```
leagueR::get_match("1160150", "euw1")
[1] Error in open.connection(con, "rb") : Could not resolve host: euw1.api.pvp.net
```
What am I doing wrong?

Thanks in advance, Simon

**Comment by stillmatic** [comment]
google says (via https://github.com/BenFradet/RiotSharp/issues/445) that "the endpoint changed from api.pvp.net to api.riotgames.com" 

try and change the code to use that endpoint instead. i haven't actually maintained this code in years so if it actually works it'd be a miracle

**Comment by systats** [comment]
Thanks for your repsonse! We got the simple solution.
